### ISSUE TITLE
ExceptionsManager.js:61 Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by deepaksisodiya** [auth0/react-native-lock#50] opened 2016-05-26 09:34 UTC
on button click i am calling a method which has below code

_onShowLock() {
    lock.show({}, (err, profile, token) => {
      console.log('Logged in!');
    });
  }

and lock.show method giving the  "Cannot read property 'init' of undefined" error in Xcode Simulator.
anything i am missing?

**Comment by hzalaz** [comment] 2016-06-06 05:21
@deepaksisodiya I can't help if you don't provide a little more info on your setup. Do you have some sample I can download and debug? Can you reproduce this issue with out sample from https://docs.auth0.com?

**Comment by KBLNY** [comment] 2016-06-06 16:56
Hi, for your info I encountered the same error. 
I had to manually linked the project, and I forgot to "Add libA0RNLock.a to your project's Build Phases ➜ Link Binary With Libraries" (cf. point #3)
How is it on your side?

**Comment by hzalaz** [comment] 2016-06-06 17:01
@KBLNY are you using `rnpm`? (https://github.com/auth0/react-native-lock#rnpm) or you just tried to configure it manually (https://github.com/auth0/react-native-lock#manually)

**Comment by hzalaz** [comment] 2016-06-06 17:02
Also #3 is no longer true since the lib changed how it should be included

**Comment by KBLNY** [comment] 2016-06-07 13:33
@hzalaz I tried `rnpm` but I got an error due to a whitespace in my project path.
I then configured it manually

**Comment by hzalaz** [comment] 2016-06-14 00:47
Closing this one. Feel free to reopen if issue shows up again

**Closed by hzalaz** 2016-06-14 00:47 UTC
Labels: question

**Comment by ajonno** [comment] 2016-11-15 04:01
hi, i came across this same crash today and wanted to see if u can help with a possible fix. 
firstly the crash only occured on Android. iOS is ok.
also, im using a single launch file in the React Native app, ie. both index.android.js and index.ios.js 'point' to a launch file ive called 'App.js'.

im requiring lock like so:
``` 
var Auth0Lock = require('react-native-lock'); 
```
then in constructor im instantiating like this:
```
const auth0_ClientId = (Platform.OS === 'ios') ?
'my ios key' :
'my droid key'

var lock = new Auth0Lock({clientId: auth0_ClientId, domain: 'cleverbean.au.auth0.com'});
```

i set a breakpoint in auth0-lock.js in the show() method which is ~ line 32
the first line of that method is crashing the app -  **LockModule** object was undefined

weird thing is that the LockModule object is ok for iOS.

is this something you could help take a look at ?

**Comment by jasonlevinsohn** [comment] 2017-02-18 04:57
I was also having this problem after using rnpm to link the lock library.  I found the import was missing in the `MainApplication.java` file.

Adding `import com.auth0.lock.react.LockReactPackage`

and then putting `new LockReactPackage()` in the `getPackages()` function fixed the problem.  This step is listed in the manual install noted above.

**Comment by athompson909** [comment] 2017-03-31 15:09
I get the same error trying to use lock on ios.  Stepping through `lock.show()` in auth0-lock.js shows me that `LockModule` is undefined.  This variable is instantiated at the beginning of auth0-lock.js: `var LockModule = NativeModules.Auth0LockModule;`  I've run `rnpm link react-native-lock` and still no success.  I'm using react native version 0.39.2

**Comment by dk0r** [comment] 2017-06-12 18:40
@athompson909  any updates
