### ISSUE TITLE
Signups don't honor scope parameters

### ISSUE THREAD

**Issue by jessebibee** [auth0/react-native-lock#91] opened 2016-09-08 22:03 UTC
The widget doesn't appear to honor scopes for the generated token when the user goes through the sign up flow.  

```
const options = {
  authParams: {
    scope: 'openid userId offline_access roles'
  }
};

lock.show(options, (err, profile, token) => {
  ...
});
```

userId is not coming back as part of the JWT token payload during a Sign Up, but does when logging in as an existing user (through a db connection).
- "react-native-lock": "0.3.0"
- "react": "15.3.0"
- "react-native": "0.32.0"

**Comment by hzalaz** [comment] 2016-09-08 22:12
@jessebibee platform? (iOS|Android)

**Comment by jessebibee** [comment] 2016-09-08 22:15
Sorry @hzalaz, iOS.

**Comment by hzalaz** [comment] 2016-09-08 22:16
@jessebibee thanks, please paste Podfile & Podfile.lock (inside `ios` folder)

**Comment by jessebibee** [comment] 2016-09-08 22:46
@hzalaz Cut down to Lock specific stuff for brevity's sake.

```
target 'mobile' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  project 'mobile', 'Debug' => :debug, 'Release' => :release 

  # Pods for mobile
  pod 'Lock', '~> 1.26'
  pod 'Lock/TouchID'
  pod 'Lock/SMS'
  pod 'Lock/Email'

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```


```
PODS:
  - Lock (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/Core (= 1.26.1)
    - Lock/UI (= 1.26.1)
    - Lock/WebView (= 1.26.1)
  - Lock/Core (1.26.1):
    - AFNetworking (~> 3.0)
    - CocoaLumberjack (~> 2.0)
  - Lock/CoreUI (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/Core
    - Masonry (~> 0.6)
  - Lock/Email (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/UI
  - Lock/SMS (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/UI
  - Lock/TouchID (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/UI
    - SimpleKeychain (~> 0.2)
    - TouchIDAuth (~> 0.1)
  - Lock/UI (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/CoreUI
  - Lock/WebView (1.26.1):
    - CocoaLumberjack (~> 2.0)
    - Lock/CoreUI
  - SimpleKeychain (0.7.0)
  - TouchIDAuth (0.2.0):
    - SimpleKeychain (~> 0.3)

DEPENDENCIES:
  - Lock (~> 1.26)
  - Lock/Email
  - Lock/SMS
  - Lock/TouchID

SPEC CHECKSUMS:
  Lock: d981a23c9ea7d2a77d7637ea83826b751df4e2f2

PODFILE CHECKSUM: 63e2e32d17e6bb9e2bca1c2ba1ce4631feb865ad

COCOAPODS: 1.0.1
```

**Comment by hzalaz** [comment] 2016-12-01 00:58
@jessebibee sorry for the delay but is this still an issue?

**Comment by hzalaz** [comment] 2017-02-21 21:13
Closing this one since I could not reproduce it.

**Closed by hzalaz** 2017-02-21 21:13 UTC
